config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'listings#search'
  resources :addresses, only: [:edit, :update, :destroy ]
  post 'listings/:id/address', to: 'listings#specify_address', as: "specify_address"
  get 'offers/offers_out'
  get 'offers/offers_in'
  resources :offers, only: [:show, :edit, :update, :destroy]
  devise_for :users
  resources :users, only: [:destroy]
  get 'listings/watchlist'
  resources :watched_items, only: [:destroy]
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
    end
  end
  root 'pages#home'
  
  get 'listings/offroad'
  get 'listings/highspeed'
  get 'listings/commuter'
  get 'listings/kids'
  post 'listings/:id/offer', to: 'listings#place_offer', as: "place_offer"
  post 'listings/:id/watched_item', to: 'listings#watch_item', as: "watch_item"
  resources :listings
  
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one :address, dependent: :destroy
  has_one_attached :picture, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :watched_items, dependent: :destroy
  validates :picture, content_type: [:png, :jpg, :jpeg]
  validates :title, presence: true
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy authorize_user place_order place_offer specify_address watch_item]
  before_action :set_offer, only: %i[ show ]
  before_action :set_form_vars, only: %i[ new edit update create ]
  before_action :authenticate_user!, except: %i[ index show offroad commuter kids highspeed search]
  before_action :authorize_user, only: %i[ edit update destroy ]

  # GET /listings or /listings.json
  def index
    # This query was implemented to retreive every instance of the Listing model
    @listings = Listing.all
  end
  
  def offroad
    # This query was implemented to retreive every instance of the Listing model where the listing's foreign key, "category id" is 1. The referenced category instance is the 'offroad' category.
    @listings = Listing.where(category_id: 1)
  end
  
  def highspeed
    # This query was implemented to retreive every instance of the Listing model where the listing's foreign key, "category id" is 2. The referenced category instance is the 'highspeed' category.
    @listings = Listing.where(category_id: 2)
  end
  
  def commuter
    # This query was implemented to retreive every instance of the Listing model where the listing's foreign key, "category id" is 3. The referenced category instance is the 'commuter' category.   
    @listings = Listing.where(category_id: 3)
  end
  
  def kids
    # This query was implemented to retreive every instance of the Listing model where the listing's foreign key, "category id" is 4. The referenced category instance is the 'kids' category.
    @listings = Listing.where(category_id: 4)
  end
  
  def watchlist
    # This query finds each instance of the WatchedItem model where it's foreign key, "user_id" is the same as the id of the current user. Each watcheditem instance references a listing and a user, so by retrieving the watched items where the user_id is the current user's, all items that the current user is watching are retrieved.
    @watchlist = WatchedItem.where(user_id: current_user.id)
    @listings = []
    @watchlist.each do |item|
    # This query selects the instance of the Listing model that the current WatchedItem references via the belongs_to relationship.
    @listings << item.listing
   end
  end

  def search
    @listings = []
    #Here each instance of the Address model is retrieved where the search parameter is included in it's postcode attribute.
    @addresses = Address.where("postcode LIKE ?", "%" + params[:q] + "%")
    @addresses.each do |address|
      # This query selects the instance of the Listing model that the current Address instance references via the belongs_to relationship.
      @listings << address.listing
    end
  end
  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    #This query sets up a new instance of the Listing model without saving it.
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    #This query sets up a new Listing without saving it, with the permitted parameters as its attributes.
    @listing = Listing.new(listing_params)
    # This query selects the User instance that the set Listing references via the belongs_to relationship.
    @listing.user = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    # This query destroys the instance of the User model which was just assigned to the @user variable
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def place_offer

    # This query creates a new instance of the Offer model and assigns the following attributes.
    Offer.create(
    # The id of the specified @listing is retrieved and assigned as the new Offer instance's referenced listing_id
    listing_id: @listing.id,
    # The user_id of the specified @listing is retrieved and assigned as the new Offer instance's referenced merchant_id
    merchant_id: @listing.user_id,
    # The user_id of the current user is retrieved and assigned as the new Offer instance's referenced offerer_id
    offerer_id: current_user.id
    )
    flash[:notice] = "Offer created! Enter the offer amount or delete offer to cancel."
    # This query first retrieves the last (therefore most recent) of the instances of the Offer model that belong to the current_user User instance as offers_out, which retrieves the offer that the user just created.
    redirect_to edit_offer_path(current_user.offers_out.last)
  end

  def specify_address
    # This query creates a new instance of the Address model and assigns the current listing's id as it's referenced listing foreign key attribute.
    Address.create(
    listing_id: @listing.id
    )
    flash[:notice] = "Please specify the address of your listing."
    # This query selects the has_one address instance that is attached to the current listing.
    redirect_to edit_address_path(@listing.address)
  end

  def watch_item
    # This query creates a new instance of the Offer model and assigns the following attributes.
    WatchedItem.create(
    # The id of the specified @listing is retrieved and assigned as the new WatchedItem instance's referenced listing_id
    listing_id: @listing.id,
    # The id of the current_user is retrieved and assigned as the new WatchedItem instance's referenced user_id
    user_id: current_user.id
    )
    flash[:notice] = "Listing added to watchlist"
    redirect_to @listing
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      # This query was implemented to find the instance of the Listing model with the same :id parameter
      @listing = Listing.find(params[:id])
    end
   
    def set_offer
      if current_user
      # This query finds the instance of the Offer model that references the currently set listing and references the current user as it's offerer. This retrieves the Offer instance that the current user has made.
      @offer = Offer.find_by(listing_id: @listing.id, offerer_id: current_user.id)
      end
    end

    def authorize_user
      # This query finds the set listing's referenced user model instance which it belongs to.
      if !current_user.admin && @listing.user != current_user
        flash[:alert] = "Access denied"
        redirect_to listings_path
      end
    end

    def set_form_vars
      #This query retrieves every instance of the Category model.
      @categories = Category.all
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :brand, :price, :description, :in_built_lighting, :double_motor, :pneumatic_tires, :has_suspension, :user_id, :picture, :category_id)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
    def user_made_offer?
        # This query looks for an instance of the Offer model that references the set listing as well as the current user.
        Offer.find_by(listing_id: @listing.id, offerer_id: current_user.id)
    end

    def item_watched?
        if current_user
        # This query looks for an instance of the WatchedItem model that references the set listing as well as the current user.
        WatchedItem.find_by(listing_id: @listing.id, user_id: current_user.id)
        end
    end

    def format_address(address)
        unwanted = ["id", "listing_id", "created_at", "updated_at"]
        formatted = ""
        address.attributes.each do |key, value|
            unless unwanted.include?(key.to_s)
                if value && value.to_s != ""
                    formatted << "#{value.to_s}, "
                end
            end
        end
        return formatted[0...-2]
    end
end

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Model %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price,  max: 50000%>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]} %>
  </div>

  <div class="field">
    <%= form.label :in_built_lighting %>
    <%= form.check_box :in_built_lighting %>
  </div>

  <div class="field">
    <%= form.label :double_motor %>
    <%= form.check_box :double_motor %>
  </div>

  <div class="field">
    <%= form.label :pneumatic_tires %>
    <%= form.check_box :pneumatic_tires %>
  </div>

  <div class="field">
    <%= form.label :has_suspension %>
    <%= form.check_box :has_suspension %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, accept: 'image/png,image/jpeg,image/jpg' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/_scootercards.html.erb
<div class='container-fluid d-flex flex-wrap'>
<% @listings.each do |listing| %>
    <div class="card mx-2 my-2" style="width: 16rem;">
    <!-- This query selects the referenced 'picture' instance of the activestorage attachment the current instance of the Listing model within the @listing array has through the has_one_attached relationship. It then retrieves the returned boolean attribute from the activerecord helper method 'attached?'.-->
    <% if listing.picture.attached?%>
    <!-- This query selects the referenced 'picture' instance of the activestorage attachment the current instance of the Listing model within the @listing array has through the has_one_attached relationship.-->
    <%= image_tag listing.picture %>
    <% else %>
    <%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default_scooter.jpeg" %>
    <% end %>
    <div class="card-body">
    <!-- This query selects the 'title' attribute of the current instance of the Listing model within the @listing array-->
      <h5 class="card-title"><%=listing.title%></h5>
    <!-- This query selects the 'description' attribute of the current instance of the Listing model within the @listing array-->
      <p class="card-text"><%=listing.description%></p>
    <!-- This query selects the 'price' attribute of the current instance of the Listing model within the @listing array-->
      <%= link_to number_to_currency(listing.price), listing, class: "btn btn-primary"%>
    </div>
    </div>
<% end %>
</div>

app/views/listings/commuter.html.erb
<h1>Commuter Scooters</h1>

<%= render 'scootercards', listings: @listings %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', @listing %>

app/views/listings/highspeed.html.erb
<h1>High-Speed Scooters</h1>

<%= render 'scootercards', listings: @listings %>

app/views/listings/index.html.erb
<h1>Browse Scooters</h1>

<form action="/search">
  <input name="q" type="text" placeholder="Search by postcode" aria-label="Postcode-search">
  <button type="submit" class='btn btn-outline-primary'>Search</button>
</form>

<%= render 'scootercards', listings: @listings %>

app/views/listings/kids.html.erb
<h1>Kids Scooters</h1>

<%= render 'scootercards', listings: @listings %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', current_user, class: 'btn btn-light' %>

app/views/listings/offroad.html.erb
<h1>Offroad Scooters</h1>

<%= render 'scootercards', listings: @listings %>

app/views/listings/search.html.erb
<h1>Browse Scooters</h1>

<form action="/search">
  <input name="q" type="text" placeholder="Search by postcode" aria-label="Postcode-search">
  <button type="submit" class='btn btn-outline-primary'>Search</button>
</form>

<%= render 'scootercards', listings: @listings %>

app/views/listings/show.html.erb
<h1>
  <!--This query selects the 'title' attribute of the set Listing model instance. -->
  Listing: "<%= @listing.title %>"
</h1>

<h4>
  <!--This query selects the 'name' attribute of the referenced (via 'belongs_to') Category instance of the set Listing. -->
  <%= @listing.category.name %> Scooter
</h4>
<!-- This query selects the referenced 'picture' instance of the activestorage attachment the current instance of the Listing model has through the has_one_attached relationship. It then retrieves the returned boolean attribute from the activerecord helper method 'attached?'.-->
<% if @listing.picture.attached?%>
<!-- This query selects the referenced 'picture' instance of the activestorage attachment the current instance of the Listing model has through the has_one_attached relationship.-->
<%= image_tag @listing.picture, alt: @listing.title  %>
<% else %>
<%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default_scooter.jpeg" %>
<% end %>

<!-- This query retrieves the 'address' attribute of the current Listing instance -->
<% if user_signed_in? && @listing.address%>
  <p>Location: <%= format_address(@listing.address)%></p>
<% elsif !user_signed_in? && @listing.address%>
  <p>Location: Please <%=link_to "log in", new_user_session_path %> to view location</p>
<% end %>

<h2 class="my-3">
<!-- This query retrieves the 'price' attribute of the current Listing instance -->
  <%= number_to_currency(@listing.price) %>
</h2>

<!-- This query retrieves the referenced User instance of the current Listing instance via the belongs_to relationship -->
<% if current_user && current_user == @listing.user || current_user && current_user.admin? %>
<div class='container-fluid d-flex flex-wrap'>
  <%= link_to 'Edit Listing', edit_listing_path(@listing), class: 'btn btn-secondary' %>
      <% if !@listing.address %>
      <%= button_to "Add address", specify_address_path, class: 'btn btn-outline-secondary mx-1' %>
      <% else %>
      <%= link_to "Edit address", edit_address_path(@listing.address), class: 'btn btn-outline-secondary mx-1' %>
      <% end %>
  <%= link_to 'Delete Listing', @listing, class: 'btn btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

<!-- This query retrieves the referenced User instance of the current Listing instance via the belongs_to relationship -->
<% if current_user && @listing.user != current_user %>
  <div class='container'>
  <% if item_watched? %>
  <%= button_to "Unwatch item", watched_item_url, method: :delete, class: "btn btn-outline-secondary mb-2"%>
  <% else %>
  <%= button_to "Watch item", watch_item_path, class: 'btn btn-secondary mb-2' %>
  <% end %>

  <% if !user_made_offer? %>
  <%= button_to "Make offer", place_offer_path, class: 'btn btn-primary mb-2' %>
  <% else %>
  <%= link_to "View Offer", offer_path(@offer), class: 'btn btn-primary mb-2' %>
  <% end %>
  </div>
<% end %>

<% if !current_user %>
  <div class='container'>
  <%= button_to "Make offer", place_offer_path, class: 'btn btn-primary mb-2' %>
  <%= button_to "Watch item", watch_item_path, class: 'btn btn-secondary mb-2' %>
  </div>
<% end %>

<div class="container my-4">
<h3>Specifications</h3>
<p>
  <strong>Brand:</strong>
  <%= @listing.brand %>
</p>


<p>
  <strong>Description:</strong>
  <!-- This query retrieves the 'description' attribute of the current Listing instance -->
  <%= @listing.description %>
</p>

<p>
  <strong>In built lighting:</strong>
  <!-- This query retrieves the 'in_built_lighting' boolean attribute of the current Listing instance -->
  <span><%= @listing.in_built_lighting ? "✅" : "❌" %></span>
</p>

<p>
  <strong>Double motor:</strong>
  <!-- This query retrieves the 'double_motor' boolean attribute of the current Listing instance -->
  <span><%= @listing.double_motor ? "✅" : "❌" %></span>
</p>

<p>
  <strong>Pneumatic tires:</strong>
  <!-- This query retrieves the 'pneumatic_tires' boolean attribute of the current Listing instance -->
  <span><%= @listing.pneumatic_tires ? "✅" : "❌" %></span>
</p>

<p>
  <strong>Has suspension:</strong>
  <!-- This query retrieves the 'has_suspension' boolean attribute of the current Listing instance -->
  <span><%= @listing.has_suspension ? "✅" : "❌" %></span>
</p>
</div>

<% if current_user && current_user == @listing.user %>
    <%= link_to "View my listings", user_path(current_user), class: 'btn btn-primary mb-2' %>
<% end %>

<% if current_user && current_user != @listing.user%>
    <div class='container'>
    <div class="card my-2" style="width: 16rem;">
      <div class="card-body">
    <h2>Merchant Details</h2>
    <!-- This query selects the referenced 'avatar' instance of the activestorage attachment the current instance of the User model has through the has_one_attached relationship. It then retrieves the returned boolean attribute from the activerecord helper method 'attached?'.-->
      <% if @listing.user.avatar.attached? %>
      <!-- This query selects the referenced 'avatar' instance of the activestorage attachment the current instance of the User model has through the has_one_attached relationship.-->
      <%= image_tag @listing.user.avatar, class: 'avatar'%>
      <% else %>
      <%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default-avatar.jpeg", class: 'avatar'%>
      <% end %>
      <!-- This query selects 'first_name' attribute of current Listing's referenced user -->
    <h3><%= @listing.user.first_name %> </h3>
    <!-- This query selects 'username' attribute of current Listing's referenced user -->
    <p class="card-subtitle text-muted"><%= link_to @listing.user.username, @listing.user %></p>
    <h5>Contact</h5>
    <!-- This query selects 'email' attribute of current Listing's referenced user -->
    <p>Email: <%= @listing.user.email %> </p>
      <% if @listing.user.mobile? %>
      <!-- This query selects 'mobile' attribute of current Listing's referenced user -->
    <p>Mobile: <%= @listing.user.mobile %> </p>
      <% end %>
        </div>
      </div>
    </div>
<% elsif current_user == @listing.user%>
      <!-- This query selects the Offer instances belonging to the current Listing instance via the has_many relationship -->
      <% if @listing.offers.count > 0 %>
      <h2 class='py-3'>Offers received</h2>
      <div class='container-fluid d-flex flex-wrap'>
      <% @listing.offers.each do |offer| %>
          <div class="card mx-2 my-2" style="width: 16rem;">
          <div class="card-body">
            <!-- This query selects the 'first_name' attribute of the Offer's referenced Offerer instance (a User) through the belongs_to relationship -->
            <h5 class="card-title">From <%=offer.offerer.first_name%></h5>
            <!-- This query selects the 'username' attribute of the Offer's referenced Offerer instance (a User) through the belongs_to relationship -->
            <p class="card-subtitle text-muted"><%= link_to offer.offerer.username, offer.offerer%></p>
            <!-- This query selects the 'message' attribute of the Offer instance -->
            <p class="card-text"><%=offer.message%></p>
            <!-- This query selects the 'price' attribute of the Offer instance -->
            <h6 class="card-text">Price offered:<%=number_to_currency(offer.price)%></h6>
            <%= link_to "View Offer", offer, class: "btn btn-primary my-1"%>
          </div>
          </div>
      <% end %>
      </div>
      <% else %>
      <h2 class='py-3'>This listing hasn't received any offers yet.</h2>
      <% end %>
  <% else %>
  <div class='container'>
  <h2> Merchant details</h2>
  <p> Please log in to view merchant's contact details.</p>
  </div>
<% end %>

app/views/listings/watchlist.html.erb
<h1>My Watchlist</h1>

<%= render 'scootercards', listings: @listings %>