config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'listings#search'
  resources :addresses, only: [:edit, :update, :destroy ]
  post 'listings/:id/address', to: 'listings#specify_address', as: "specify_address"
  get 'offers/offers_out'
  get 'offers/offers_in'
  resources :offers, only: [:show, :edit, :update, :destroy]
  devise_for :users
  resources :users, only: [:destroy]
  get 'listings/watchlist'
  resources :watched_items, only: [:destroy]
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
    end
  end
  root 'pages#home'
  
  get 'listings/offroad'
  get 'listings/highspeed'
  get 'listings/commuter'
  get 'listings/kids'
  post 'listings/:id/offer', to: 'listings#place_offer', as: "place_offer"
  post 'listings/:id/watched_item', to: 'listings#watch_item', as: "watch_item"
  resources :listings
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar, dependent: :destroy
  validates :avatar, content_type: [:png, :jpg, :jpeg]
  validates :first_name, presence: true, format: {with: /[a-zA-Z]/, message: "Only alphabetical characters allowed for first name"}

  has_many :listings, dependent: :destroy
  has_many :watched_items, dependent: :destroy

  has_many :offers_in, foreign_key: "merchant_id", class_name: "Offer", dependent: :destroy
  has_many :offers_out, foreign_key: "offerer_id", class_name: "Offer", dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!  

  def index
    # This query was implemented to retreive every instance of the User model
    @users = User.all
  end

  def show
    # This query was implemented to find the instance of the User model with the same :id parameter
    @user = User.find(params[:id])
  end

  def edit
    # This query uses devise's current_user helper method to assign the instance of the User model which is currently logged in to the @user variable
    @user = current_user
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to current_user, notice: 'Profile updated.'}
      else
        format.html { render :edit }
      end
    end
  end

  def delete_image
    image = ActiveStorage::Attachment.find(params[:image_id])
    if current_user == image.record || current_user.admin?
      image.purge
      redirect_back(fallback_location: request.referer)
    else
      redirect_to root_path, notice: "Access denied."
    end
  end

  def destroy
    # This query was implemented to find the instance of the User model with the same :id parameter
    @user = User.find(params[:id])
    # This query destroys the instance of the User model which was just assigned to the @user variable
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Account successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :bio,
      :first_name,
      :avatar,
      :mobile
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <% if user.avatar.attached? %>
      <%= image_tag user.avatar, class: 'avatar'%>
      <div>
      <%= link_to "Remove Image",
                  delete_image_user_path(image_id: user.avatar.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' }
      %>
      </div>
    <% else %>
      <%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default-avatar.jpeg", class: 'avatar' %>
    <% end %>
  </div>

  <div>
    <%= form.file_field :avatar %>
  </div>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.telephone_field :mobile, minlength: 10, maxlength: 10 %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
    <%= link_to "Go back", user_path(current_user), class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>ScooterBay Users</h1>

<ul>
    <% @users.each do |user| %>
    <li>
    <!-- This query retrieves the username attribute of the currently referenced instance of the User model -->
        <%= link_to user.username, user %>
    </li>
    <% end %>
</ul>

app/views/users/show.html.erb
<% if @user.avatar.attached? %>
<!-- This query retrieves the avatar attribute of the currently referenced instance of the User model (which is an Activerecord attachment) -->
<%= image_tag @user.avatar, class: 'avatar'%>
<% else %>
<%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default-avatar.jpeg", class: 'avatar'%>
<% end %>

<!-- This query retrieves the first_name attribute of the currently referenced instance of the User model -->
<h1><%=@user.first_name%></h1>
<!-- This query retrieves the created_at attribute of the currently referenced instance of the User model -->
<p class="text-muted">Member since <%=@user.created_at.to_date%></p>

<% if @user.bio? %>
<h2>Bio</h2>
<!-- This query retrieves the bio attribute of the currently referenced instance of the User model -->
<p><%=@user.bio%></p>
<% end %>

<% if user_signed_in? %>
<h4>Contact</h4>
<!-- This query retrieves the email attribute of the currently referenced instance of the User model -->
<p>Email: <%=@user.email%></p>
  <% if @user.mobile? %>
<!-- This query retrieves the mobile attribute of the currently referenced instance of the User model -->
  <p>Mobile: <%=@user.mobile%></p>
  <% end %>
<% end %>

<% if current_user.admin? || current_user.id == @user.id %>
<%= link_to "Edit Profile", edit_user_path(@user), class: 'btn btn-primary' %>
<%= link_to 'Delete Account', @user, class: 'btn btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<% if current_user == @user %>
<h1 class='my-3'>My Listings</h1>
<% else %>
<!-- This query retrieves the first_name attribute of the currently referenced instance of the User model -->
<h1 class='my-3'>Listings by <%=@user.first_name%></h1>
<% end %>

<div class='container-fluid d-flex flex-wrap my-5'>
<% @user.listings.each do |listing| %>
    <div class="card mx-2 my-2" style="width: 16rem;">
    <!-- This query selects the referenced 'picture' instance of the activestorage attachment the current instance of the Listing model has through the has_one_attached relationship. It then retrieves the returned boolean attribute from the activerecord helper method 'attached?'.-->
    <% if listing.picture.attached?%>
    <!-- This query selects the referenced 'picture' instance of the activestorage attachment the current instance of the Listing model has through the has_one_attached relationship.-->
    <%= image_tag listing.picture %>
    <% else %>
    <%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default_scooter.jpeg" %>
    <% end %>
    <div class="card-body">
    
<!-- This query retrieves the title attribute of the currently referenced instance of the Listing model -->
      <h5 class="card-title"><%=listing.title%></h5>
<!-- This query retrieves the description attribute of the currently referenced instance of the Listing model -->
      <p class="card-text"><%=listing.description%></p>
<!-- This query retrieves the price attribute of the currently referenced instance of the Listing model -->
      <%= link_to number_to_currency(listing.price), listing, class: "btn btn-primary"%>
      <% if listing.user == current_user || current_user.admin?%>
      <%= link_to 'Delete Listing', listing, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    </div>
<% end %>
</div>

<% if current_user == @user %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-success'%>
<% end %>