config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'listings#search'
  resources :addresses, only: [:edit, :update, :destroy ]
  post 'listings/:id/address', to: 'listings#specify_address', as: "specify_address"
  get 'offers/offers_out'
  get 'offers/offers_in'
  resources :offers, only: [:show, :edit, :update, :destroy]
  devise_for :users
  resources :users, only: [:destroy]
  get 'listings/watchlist'
  resources :watched_items, only: [:destroy]
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
    end
  end
  root 'pages#home'
  
  get 'listings/offroad'
  get 'listings/highspeed'
  get 'listings/commuter'
  get 'listings/kids'
  post 'listings/:id/offer', to: 'listings#place_offer', as: "place_offer"
  post 'listings/:id/watched_item', to: 'listings#watch_item', as: "watch_item"
  resources :listings
  
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "ScooterBay", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
            <%= link_to "Scooters", listings_path, class: 'nav-link' %>
        <% if !user_signed_in? %>
            <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
        <% else %>
            <%= link_to "Users", users_path, class: 'nav-link' %>
            <%= link_to "Account", user_path(current_user), class: 'nav-link' %>
            <%= link_to "Watchlist", listings_watchlist_path, class: 'nav-link' %>
            <%= link_to "Offers Made", offers_offers_out_path, class: 'nav-link' %>
            <%= link_to "Offers Received", offers_offers_in_path, class: 'nav-link' %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>