config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'listings#search'
  resources :addresses, only: [:edit, :update, :destroy ]
  post 'listings/:id/address', to: 'listings#specify_address', as: "specify_address"
  get 'offers/offers_out'
  get 'offers/offers_in'
  resources :offers, only: [:show, :edit, :update, :destroy]
  devise_for :users
  resources :users, only: [:destroy]
  get 'listings/watchlist'
  resources :watched_items, only: [:destroy]
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
    end
  end
  root 'pages#home'
  
  get 'listings/offroad'
  get 'listings/highspeed'
  get 'listings/commuter'
  get 'listings/kids'
  post 'listings/:id/offer', to: 'listings#place_offer', as: "place_offer"
  post 'listings/:id/watched_item', to: 'listings#watch_item', as: "watch_item"
  resources :listings
  
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :listing
  belongs_to :offerer, foreign_key: "offerer_id", class_name: "User"
  belongs_to :merchant, foreign_key: "merchant_id", class_name: "User"
  validates :price, allow_nil: true, numericality: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
    before_action :set_offer, only: %i[ show edit update destroy authorize_user]
    before_action :authorize_user, only: %i[ edit update destroy show ]
    before_action :authenticate_user!
   
    def index
        # This query was implemented to retreive every instance of the Offer model
        @offers = Offer.all
    end
   
    def show
    end

    def offers_in
        #This query retrieves offers that belong to current user via the offers_in / merchant id reference, which retrieves the offer instances where the current user's id is the merchant_id.
        @offers_in = current_user.offers_in
    end

    def offers_out
        #This query retrieves offers that belong to current user via the offers_out / offerer id reference, which retrieves the offer instances where the current user's id is the offerer_id.
        @offers_out = current_user.offers_out
    end
  
    def destroy
      # This query was implemented to find the instance of the Offer model with the same :id parameter
      @offer = Offer.find(params[:id])
      # This query finds the instance of the listing model that the @offer belongs to via the 'belongs to' relationship.
      @tmp_listing = @offer.listing
      # This query deletes the assigned instance of the Offer model from the database
      @offer.destroy
  
      respond_to do |format|
        format.html { redirect_to @tmp_listing, notice: "Offer successfully removed." }
        format.json { head :no_content }
      end
    end

    def new
        #This query sets up a new Offer without saving it
        @offer = Offer.new
    end

    def edit
    end

    def update
        respond_to do |format|
          if @offer.update(offer_params)
            format.html { redirect_to offer_url(@offer), notice: "Offer was successfully updated." }
            format.json { render :show, status: :ok, location: @offer }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @offer.errors, status: :unprocessable_entity }
          end
        end
    end

  private

    def authorize_user
      # current_user.admin retrieves the boolean attribute of User instance 'admin'
      if !current_user.admin && (current_user != @offer.merchant && current_user != @offer.offerer)
        flash[:alert] = "Access denied"
        redirect_to listings_path
      end
    end

    def set_offer
      # This query was implemented to find the instance of the Offer model with the same :id parameter
        @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
    params.require(:offer).permit(:price, :message)
    end
end
  

app/views/offers/_form.html.erb
<%= form_with(model: offer) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Offer_price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :Message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<!-- This query retrieves the title attribute of the Listing model instance that the currently referenced Offer instance references -->
<h1>Offer for <%=@offer.listing.title%></h1>

<%= render 'form', offer: @offer %>
<%= button_to "Cancel Offer", @offer, method: :delete, class: "btn btn-secondary"%>
<p>
  <strong>Model:</strong>
<!-- This query retrieves the title attribute of the Listing model instance that the currently referenced Offer instance references -->
  <%= @offer.listing.title %>
</p>

<% if @offer.listing.picture.attached?%>
<!-- This query retrieves the referenced Activestorage attachment of the Listing model instance that the currently referenced Offer instance references -->
<%= image_tag @offer.listing.picture, alt: @offer.listing.title  %>
<% else %>
<%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default_scooter.jpeg" %>
<% end %>

<p class="mt-2">
  Listing price:
  <strong>
<!-- This query retrieves the price attribute of the Listing model instance that the currently referenced Offer instance references -->
  <%= number_to_currency(@offer.listing.price) %>
  </strong>
</p>

<div class="card my-2" style="width: 16rem;">
  <div class="card-body">
    <h2>Merchant Details</h2>
    <% if @offer.merchant.avatar.attached? %>
<!-- This query retrieves the referenced Activestorage attachment of the User model instance that the currently referenced Offer instance references -->
    <%= image_tag @offer.merchant.avatar, class: 'avatar'%>
    <% else %>
    <%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default-avatar.jpeg", class: 'avatar'%>
    <% end %>
<!-- This query retrieves the first_name attribute of the User model instance that the currently referenced Offer instance references -->
    <h3><%= @offer.merchant.first_name %> </h3>
<!-- This query retrieves the username attribute of the User model instance that the currently referenced Offer instance references -->
    <p class="card-subtitle text-muted"><%= link_to @offer.merchant.username, @offer.merchant %> </p>
    <h5>Contact</h5>
<!-- This query retrieves the email attribute of the User model instance that the currently referenced Offer instance references -->
    <p>Email: <%= @offer.merchant.email %> </p>
    <% if @offer.merchant.mobile? %>
<!-- This query retrieves the mobile attribute of the User model instance that the currently referenced Offer instance references -->
    <p> Mobile: <%= @offer.merchant.mobile %></p>
    <% end %>
  </div>
</div>

<%= link_to 'Back', @offer, class: 'btn btn-light' %>

app/views/offers/index.html.erb
<h1>All Offers</h1>

<% @offers.each do |offer| %>
<!-- This query retrieves the title attribute of the Listing instance that the currently referenced Offer instance references-->
    <h2><%=offer.listing.title%><h2>
<% end %>

app/views/offers/offers_in.html.erb
<% if @offers_in.size > 0 %>
  <h1>Offers Received</h1>

  <div class='container-fluid d-flex flex-wrap'>
  <% @offers_in.each do |offer| %>
      <div class="card mx-2 my-2" style="width: 16rem;">
      <% if offer.listing.picture.attached?%>
<!-- This query retrieves the referenced Activestorage attachment of the Listing model instance that the currently referenced Offer instance references -->     
      <%= image_tag offer.listing.picture %>
      <% else %>
      <%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default_scooter.jpeg" %>
      <% end %>
      <div class="card-body">
<!-- This query retrieves the title attribute of the Listing model instance that the currently referenced Offer instance references -->      
        <h5 class="card-title"><%=offer.listing.title%></h5>
<!-- This query retrieves the description attribute of the Listing model instance that the currently referenced Offer instance references -->      
        <p class="card-text"><%=offer.listing.description%></p>
<!-- This query retrieves the first_name attribute of the User model instance that the currently referenced Offer instance references -->      
        <h5 class="card-title">From <%=offer.offerer.first_name%></h5>
<!-- This query retrieves the price attribute currently referenced Offer instance -->
        <h6 class="card-text">Price offered: <%=number_to_currency(offer.price)%></h6>
<!-- This query retrieves the username attribute of the User model instance that the currently referenced Offer instance references -->      
        <p class="card-subtitle text-muted"><%= link_to offer.offerer.username, offer.offerer%></p>
<!-- This query retrieves the message attribute currently referenced Offer instance -->
        <p class="card-text"><%=offer.message%></p>
        <%= link_to "View Offer", offer, class: "btn btn-primary my-1"%>
      </div>
      </div>
  <% end %>
<% else %>
  <h1>Your listings haven't received any offers yet.</h1>
  <p>Click <%= link_to "here", current_user %> to view your listings</p>
<% end %>
</div>

app/views/offers/offers_out.html.erb
<% if @offers_out.size > 0 %>
  <h1>Offers Out</h1>

  <div class='container-fluid d-flex flex-wrap'>
  <% @offers_out.each do |offer| %>
      <div class="card mx-2 my-2" style="width: 16rem;">
      <% if offer.listing.picture.attached?%>
<!-- This query retrieves the referenced Activestorage attachment of the Listing model instance that the currently referenced Offer instance references -->      
      <%= image_tag offer.listing.picture %>
      <% else %>
      <%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default_scooter.jpeg" %>
      <% end %>
      <div class="card-body">
<!-- This query retrieves the title attribute of the Listing model instance that the currently referenced Offer instance references -->
        <h5 class="card-title"><%=offer.listing.title%></h5>
<!-- This query retrieves the description attribute of the Listing model instance that the currently referenced Offer instance references -->
        <p class="card-text"><%=offer.listing.description%></p>
<!-- This query retrieves the price attribute of the currently referenced Offer instance -->
        <h6 class="card-text">Price offered: <%=number_to_currency(offer.price)%></h6>
        <%= link_to "View Offer", offer, class: "btn btn-primary my-2"%>
        <%= button_to "Cancel Offer", offer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
      </div>
      </div>
  <% end %>
  </div>
<% else %>
  <h1>You haven't made any offers yet.</h1>
  <p>Click <%= link_to "here", listings_path %> to browse scooters.</p>
<% end %>

app/views/offers/show.html.erb
<% if current_user == @offer.merchant%>
<!-- This query retrieves the title attribute of the Listing model instance that the currently referenced Offer instance references -->
<h2>Offer received for listing: "<%= @offer.listing.title %>"</h2>
<% else %>
<!-- This query retrieves the title attribute of the Listing model instance that the currently referenced Offer instance references -->
<h2>Your offer for listing: "<%= @offer.listing.title %>"</h2>
<% end %>

<% if @offer.listing.picture.attached?%>
<!-- This query retrieves the referenced Activestorage attachment of the Listing model instance that the currently referenced Offer instance references -->
<%= image_tag @offer.listing.picture, alt: @offer.listing.title  %>
<% else %>
<%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default_scooter.jpeg" %>
<% end %>

<p class="mt-2">
  Listing price:
  <strong>
<!-- This query retrieves the price attribute of the Listing model instance that the currently referenced Offer instance references -->  
  <%= number_to_currency(@offer.listing.price) %>
  </strong>
</p>

<p>
  Price offered:
  <strong>
<!-- This query retrieves the price attribute currently of the referenced Offer instance -->  
  <%= number_to_currency(@offer.price) %>
  </strong>

<p>
<!-- This query retrieves the message attribute of the currently referenced Offer instance -->
  Message: <%= @offer.message %>
</p>

<!-- This query retrieves the created_at attribute of the currently referenced Offer instance -->
<p class="text-muted">Offer made <%= time_ago_in_words(@offer.created_at) %> ago</p>

<!-- This query retrieves the User instance that currently referenced Offer instance references -->
<% if current_user && current_user == @offer.offerer %>
<p><%= link_to "Edit Offer", edit_offer_path, class: 'btn btn-primary'%></p>
<% end %>

<!-- This query retrieves the Listing instance that the currently referenced Offer instance references -->
<%= link_to "View Listing", @offer.listing, class: 'btn btn-secondary mb-2' %>

<!-- This query retrieves the User instance that the currently referenced Offer instance references -->
<% if current_user && current_user == @offer.merchant %>
  <div class="card my-2" style="width: 16rem;">
    <div class="card-body">
      <h2>Buyer Details</h2>
      <% if @offer.offerer.avatar.attached? %>
<!-- This query retrieves the referenced Activestorage attachment of the User model instance that the currently referenced Offer instance references -->      
      <%= image_tag @offer.offerer.avatar, class: 'avatar'%>
      <% else %>
      <%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default-avatar.jpeg", class: 'avatar'%>
      <% end %>
<!-- This query retrieves the first_name attribute of the User model instance that the currently referenced Offer instance references -->      
      <h3><%= @offer.offerer.first_name %> </h3>
<!-- This query retrieves the username attribute of the User model instance that the currently referenced Offer instance references -->      
      <p class="card-subtitle text-muted"><%= link_to @offer.offerer.username, @offer.offerer%></p>
      <h5>Contact</h5>
<!-- This query retrieves the email attribute of the User model instance that the currently referenced Offer instance references -->      
      <p>Email: <%= @offer.offerer.email %> </p>
      <% if @offer.offerer.mobile? %>
<!-- This query retrieves the mobile attribute of the User model instance that the currently referenced Offer instance references -->      
      <p>Mobile: <%= @offer.offerer.mobile %> </p>
      <% end %>
      </div>
  </div>
<% elsif current_user && current_user == @offer.offerer %>
  <div class="card my-2" style="width: 16rem;">
    <div class="card-body">
      <h2>Merchant Details</h2>
      <% if @offer.merchant.avatar.attached? %>
<!-- This query retrieves the referenced Activestorage attachment of the User model instance that the currently referenced Offer instance references -->      
      <%= image_tag @offer.merchant.avatar, class: 'avatar'%>
      <% else %>
      <%= image_tag "https://scooterbay-public-images.s3.ap-southeast-2.amazonaws.com/default-avatar.jpeg", class: 'avatar'%>
      <% end %>
<!-- This query retrieves the first_name attribute of the User model instance that the currently referenced Offer instance references -->      
      <h3><%= @offer.merchant.first_name %></h3>
      <p class="card-subtitle text-muted"><%= link_to @offer.merchant.username, @offer.merchant%></p>
      <h5>Contact</h5>
<!-- This query retrieves the email attribute of the User model instance that the currently referenced Offer instance references -->      
      <p>Email: <%= @offer.merchant.email %> </p>
        <% if @offer.merchant.mobile? %>
<!-- This query retrieves the mobile attribute of the User model instance that the currently referenced Offer instance references -->      
        <p>Mobile: <%= @offer.merchant.mobile %> </p>
        <% end %>
      <% end %>  
    </div>
  </div>